### PR TITLE
Remove usage of cabal.config from stackage snapshot

### PR DESCRIPTION
**Pull request by harshavardhana**
This is not really necessary with cabal sandbox, in-fact the
version number for transformers-0.4.4 listed in this config
conflicts with ghc-7.10.2

Better to avoid it since there is no real requirement on a specific
transformers version for this project. 

`cabal update` would satisfy these requirements in any-case.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Let me know if breaks any of your builds..

**Comment by dfordivam** [comment]
Even I had some conflicts so deleted this in my local repo.
And I don't use cabal sandbox, simple cabal build and cabal install works fine for me. (I do have a global cabal.config from stackage).
@vu3rdd ok to merge this?

**Comment by harshavardhana** [comment]
> And I don't use cabal sandbox, simple cabal build and cabal install works fine for me. (I do have a global cabal.config from stackage).
> @vu3rdd ok to merge this?

The problem with cabal.config at top level is that it installs the packages present in this file alone, leading it to really clobber up the system with vague dependency problems - until i progressively reached `cabal hell` . 

I ended up re-installing ghc 4 times yesterday trying to figure out what is going on :-).

**Comment by vu3rdd** [comment]
Yes, I am totally fine merging this. 

FYI, I am now using stack. It makes things much simpler (vu3rdd/functorrent).

**Pull request merged**
