### PR TITLE
Run HLint as a test suite.

### PR DESCRIPTION
**Pull request by vu3rdd**
Implements issue #14.

### CODE REVIEW

**Comment by jaseemabid** [comment]
Build times just went from ~3min to ~9m just like that. :(

**Comment by vu3rdd** [comment]
:( Didn't notice that. I think haskell-src-exts needs tons of dependencies. Is there a way one could disable particular tests in travis?

**Comment by jaseemabid** [comment]
@vu3rdd Running hlint locally might be good enough. Its code suggestions, which we have to fix by hand.

**Comment by vu3rdd** [comment]
@jaseemabid A lot of projects run hlint as a test, so that one could simplify the code. Anyway.. I will disable it.

**Comment by jaseemabid** [comment]
@vu3rdd I'm fine either way.

**Pull request merged**
